name: RulePR

on: [pull_request]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add comment to PR
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: ${{ vars.MESSAGE_PR }}
        run: |
          curl -X POST "$URL" -H "Content-Type: application/json" -H "Authorization: token $GITHUB_TOKEN" --data '{ "body": "${{ vars.MESSAGE_PR }}" }'