name: Mirror Stable BackEnd

on:
  push:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Pull and Restart
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: 135.181.165.228
            username: root
            password: ${{ secrets.PASSWORD }}
            port: 22
            command_timeout: 30m
            script: |
              cd /var/AREA/StableBackEnd
              git pull
              npm i
              pm2 restart StableBackEnd
