name: Test start API

on: [push, pull_request]

jobs:
  compile-and-start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          timeout 3m npm i --legacy-peer-deps || exit 1

      - name: Execute
        run: |
          timeout 30s npm start || exit 0

      - name: Check Result
        run: |
          if [ $? -eq 0 ]; then
            echo "The program has timeout successfully"
          else
            echo "The program send error"
            exit 1
          fi